package cn.xinzhili.chat.model;

import cn.xinzhili.chat.api.UserStatus;
import java.time.LocalDateTime;

public class MemberStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.doctor_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.assistant_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private Long assistantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.assistant_status
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private UserStatus assistantStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.created_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.updated_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_member_status.deleted_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    private LocalDateTime deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.id
     *
     * @return the value of s_message.t_member_status.id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.id
     *
     * @param id the value for s_message.t_member_status.id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.doctor_id
     *
     * @return the value of s_message.t_member_status.doctor_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.doctor_id
     *
     * @param doctorId the value for s_message.t_member_status.doctor_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.assistant_id
     *
     * @return the value of s_message.t_member_status.assistant_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public Long getAssistantId() {
        return assistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.assistant_id
     *
     * @param assistantId the value for s_message.t_member_status.assistant_id
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setAssistantId(Long assistantId) {
        this.assistantId = assistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.assistant_status
     *
     * @return the value of s_message.t_member_status.assistant_status
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public UserStatus getAssistantStatus() {
        return assistantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.assistant_status
     *
     * @param assistantStatus the value for s_message.t_member_status.assistant_status
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setAssistantStatus(UserStatus assistantStatus) {
        this.assistantStatus = assistantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.created_at
     *
     * @return the value of s_message.t_member_status.created_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.created_at
     *
     * @param createdAt the value for s_message.t_member_status.created_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.updated_at
     *
     * @return the value of s_message.t_member_status.updated_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.updated_at
     *
     * @param updatedAt the value for s_message.t_member_status.updated_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_member_status.deleted_at
     *
     * @return the value of s_message.t_member_status.deleted_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_member_status.deleted_at
     *
     * @param deletedAt the value for s_message.t_member_status.deleted_at
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_member_status
     *
     * @mbggenerated Tue May 15 10:37:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", doctorId=").append(doctorId);
        sb.append(", assistantId=").append(assistantId);
        sb.append(", assistantStatus=").append(assistantStatus);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append("]");
        return sb.toString();
    }
}