package cn.xinzhili.chat.model;

import cn.xinzhili.chat.api.MessageType;
import cn.xinzhili.chat.api.RoleType;
import java.time.LocalDateTime;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.sender_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private Long senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.sender_role_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private RoleType senderRoleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.session_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private Long sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.content
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.message_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private MessageType messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.receiver_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private Long receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.created_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.updated_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_message.t_message.deleted_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    private LocalDateTime deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.id
     *
     * @return the value of s_message.t_message.id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.id
     *
     * @param id the value for s_message.t_message.id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.sender_id
     *
     * @return the value of s_message.t_message.sender_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.sender_id
     *
     * @param senderId the value for s_message.t_message.sender_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.sender_role_type
     *
     * @return the value of s_message.t_message.sender_role_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public RoleType getSenderRoleType() {
        return senderRoleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.sender_role_type
     *
     * @param senderRoleType the value for s_message.t_message.sender_role_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setSenderRoleType(RoleType senderRoleType) {
        this.senderRoleType = senderRoleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.session_id
     *
     * @return the value of s_message.t_message.session_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.session_id
     *
     * @param sessionId the value for s_message.t_message.session_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.content
     *
     * @return the value of s_message.t_message.content
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.content
     *
     * @param content the value for s_message.t_message.content
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.message_type
     *
     * @return the value of s_message.t_message.message_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public MessageType getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.message_type
     *
     * @param messageType the value for s_message.t_message.message_type
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.receiver_id
     *
     * @return the value of s_message.t_message.receiver_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.receiver_id
     *
     * @param receiverId the value for s_message.t_message.receiver_id
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.created_at
     *
     * @return the value of s_message.t_message.created_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.created_at
     *
     * @param createdAt the value for s_message.t_message.created_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.updated_at
     *
     * @return the value of s_message.t_message.updated_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.updated_at
     *
     * @param updatedAt the value for s_message.t_message.updated_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_message.t_message.deleted_at
     *
     * @return the value of s_message.t_message.deleted_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_message.t_message.deleted_at
     *
     * @param deletedAt the value for s_message.t_message.deleted_at
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", senderId=").append(senderId);
        sb.append(", senderRoleType=").append(senderRoleType);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", content=").append(content);
        sb.append(", messageType=").append(messageType);
        sb.append(", receiverId=").append(receiverId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append("]");
        return sb.toString();
    }
}