package cn.xinzhili.chat.model;

import cn.xinzhili.chat.api.RoleType;
import cn.xinzhili.chat.api.SessionType;
import cn.xinzhili.chat.api.Type;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class SessionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public SessionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> initiatorRoleTypeCriteria;

        protected List<Criterion> typeCriteria;

        protected List<Criterion> sessionTypeCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            initiatorRoleTypeCriteria = new ArrayList<Criterion>();
            typeCriteria = new ArrayList<Criterion>();
            sessionTypeCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getInitiatorRoleTypeCriteria() {
            return initiatorRoleTypeCriteria;
        }

        protected void addInitiatorRoleTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            initiatorRoleTypeCriteria.add(new Criterion(condition, value, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        protected void addInitiatorRoleTypeCriterion(String condition, RoleType value1, RoleType value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            initiatorRoleTypeCriteria.add(new Criterion(condition, value1, value2, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getTypeCriteria() {
            return typeCriteria;
        }

        protected void addTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            typeCriteria.add(new Criterion(condition, value, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        protected void addTypeCriterion(String condition, Type value1, Type value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            typeCriteria.add(new Criterion(condition, value1, value2, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getSessionTypeCriteria() {
            return sessionTypeCriteria;
        }

        protected void addSessionTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            sessionTypeCriteria.add(new Criterion(condition, value, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        protected void addSessionTypeCriterion(String condition, SessionType value1, SessionType value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            sessionTypeCriteria.add(new Criterion(condition, value1, value2, "cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || initiatorRoleTypeCriteria.size() > 0
                || typeCriteria.size() > 0
                || sessionTypeCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(initiatorRoleTypeCriteria);
                allCriteria.addAll(typeCriteria);
                allCriteria.addAll(sessionTypeCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIsNull() {
            addCriterion("initiator_id is null");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIsNotNull() {
            addCriterion("initiator_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdEqualTo(Long value) {
            addCriterion("initiator_id =", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotEqualTo(Long value) {
            addCriterion("initiator_id <>", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdGreaterThan(Long value) {
            addCriterion("initiator_id >", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("initiator_id >=", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdLessThan(Long value) {
            addCriterion("initiator_id <", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdLessThanOrEqualTo(Long value) {
            addCriterion("initiator_id <=", value, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdIn(List<Long> values) {
            addCriterion("initiator_id in", values, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotIn(List<Long> values) {
            addCriterion("initiator_id not in", values, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdBetween(Long value1, Long value2) {
            addCriterion("initiator_id between", value1, value2, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorIdNotBetween(Long value1, Long value2) {
            addCriterion("initiator_id not between", value1, value2, "initiatorId");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeIsNull() {
            addCriterion("initiator_role_type is null");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeIsNotNull() {
            addCriterion("initiator_role_type is not null");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeEqualTo(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type =", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeNotEqualTo(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type <>", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeGreaterThan(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type >", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeGreaterThanOrEqualTo(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type >=", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeLessThan(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type <", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeLessThanOrEqualTo(RoleType value) {
            addInitiatorRoleTypeCriterion("initiator_role_type <=", value, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeIn(List<RoleType> values) {
            addInitiatorRoleTypeCriterion("initiator_role_type in", values, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeNotIn(List<RoleType> values) {
            addInitiatorRoleTypeCriterion("initiator_role_type not in", values, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeBetween(RoleType value1, RoleType value2) {
            addInitiatorRoleTypeCriterion("initiator_role_type between", value1, value2, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andInitiatorRoleTypeNotBetween(RoleType value1, RoleType value2) {
            addInitiatorRoleTypeCriterion("initiator_role_type not between", value1, value2, "initiatorRoleType");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNull() {
            addCriterion("organization_id is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNotNull() {
            addCriterion("organization_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdEqualTo(Long value) {
            addCriterion("organization_id =", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotEqualTo(Long value) {
            addCriterion("organization_id <>", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThan(Long value) {
            addCriterion("organization_id >", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("organization_id >=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThan(Long value) {
            addCriterion("organization_id <", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThanOrEqualTo(Long value) {
            addCriterion("organization_id <=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIn(List<Long> values) {
            addCriterion("organization_id in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotIn(List<Long> values) {
            addCriterion("organization_id not in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdBetween(Long value1, Long value2) {
            addCriterion("organization_id between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotBetween(Long value1, Long value2) {
            addCriterion("organization_id not between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Type value) {
            addTypeCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Type value) {
            addTypeCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Type value) {
            addTypeCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Type value) {
            addTypeCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Type value) {
            addTypeCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Type value) {
            addTypeCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Type> values) {
            addTypeCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Type> values) {
            addTypeCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Type value1, Type value2) {
            addTypeCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Type value1, Type value2) {
            addTypeCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSessionTypeIsNull() {
            addCriterion("session_type is null");
            return (Criteria) this;
        }

        public Criteria andSessionTypeIsNotNull() {
            addCriterion("session_type is not null");
            return (Criteria) this;
        }

        public Criteria andSessionTypeEqualTo(SessionType value) {
            addSessionTypeCriterion("session_type =", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeNotEqualTo(SessionType value) {
            addSessionTypeCriterion("session_type <>", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeGreaterThan(SessionType value) {
            addSessionTypeCriterion("session_type >", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeGreaterThanOrEqualTo(SessionType value) {
            addSessionTypeCriterion("session_type >=", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeLessThan(SessionType value) {
            addSessionTypeCriterion("session_type <", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeLessThanOrEqualTo(SessionType value) {
            addSessionTypeCriterion("session_type <=", value, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeIn(List<SessionType> values) {
            addSessionTypeCriterion("session_type in", values, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeNotIn(List<SessionType> values) {
            addSessionTypeCriterion("session_type not in", values, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeBetween(SessionType value1, SessionType value2) {
            addSessionTypeCriterion("session_type between", value1, value2, "sessionType");
            return (Criteria) this;
        }

        public Criteria andSessionTypeNotBetween(SessionType value1, SessionType value2) {
            addSessionTypeCriterion("session_type not between", value1, value2, "sessionType");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(LocalDateTime value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(LocalDateTime value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<LocalDateTime> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(LocalDateTime value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNull() {
            addCriterion("deleted_at is null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNotNull() {
            addCriterion("deleted_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtEqualTo(LocalDateTime value) {
            addCriterion("deleted_at =", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotEqualTo(LocalDateTime value) {
            addCriterion("deleted_at <>", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThan(LocalDateTime value) {
            addCriterion("deleted_at >", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("deleted_at >=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThan(LocalDateTime value) {
            addCriterion("deleted_at <", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("deleted_at <=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIn(List<LocalDateTime> values) {
            addCriterion("deleted_at in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotIn(List<LocalDateTime> values) {
            addCriterion("deleted_at not in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("deleted_at between", value1, value2, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("deleted_at not between", value1, value2, "deletedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_message.t_session
     *
     * @mbggenerated do_not_delete_during_merge Tue May 08 17:07:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}