package cn.xinzhili.chat.dao;

import cn.xinzhili.chat.model.GroupMemberDetail;
import cn.xinzhili.chat.model.GroupMemberDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GroupMemberDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int countByExample(GroupMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int deleteByExample(GroupMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    @Update({
        "update s_message.t_group_member_detail",
        "set deleted_at = now()",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    @Select({
        "insert into s_message.t_group_member_detail (session_id, sender_id, ",
        "sender_role_type, ",
        "receiver_id, receiver_unread_count, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{sessionId,jdbcType=BIGINT}, #{senderId,jdbcType=BIGINT}, ",
        "#{senderRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{receiverId,jdbcType=BIGINT}, #{receiverUnreadCount,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})", 
        " returning id"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    long insertReturningId(GroupMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    @Insert({
        "insert into s_message.t_group_member_detail (session_id, sender_id, ",
        "sender_role_type, ",
        "receiver_id, receiver_unread_count, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{sessionId,jdbcType=BIGINT}, #{senderId,jdbcType=BIGINT}, ",
        "#{senderRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{receiverId,jdbcType=BIGINT}, #{receiverUnreadCount,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(GroupMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    long insertSelectiveReturningId(GroupMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int insertSelective(GroupMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    List<GroupMemberDetail> selectByExample(GroupMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    @Select({
        "select",
        "id, session_id, sender_id, sender_role_type, receiver_id, receiver_unread_count, ",
        "created_at, updated_at, deleted_at",
        "from s_message.t_group_member_detail",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.xinzhili.chat.dao.GroupMemberDetailMapper.BaseResultMap")
    GroupMemberDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") GroupMemberDetail record, @Param("example") GroupMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int updateByExample(@Param("record") GroupMemberDetail record, @Param("example") GroupMemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    int updateByPrimaryKeySelective(GroupMemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_group_member_detail
     *
     * @mbggenerated Fri May 11 16:14:04 CST 2018
     */
    @Update({
        "update s_message.t_group_member_detail",
        "set session_id = #{sessionId,jdbcType=BIGINT},",
          "sender_id = #{senderId,jdbcType=BIGINT},",
          "sender_role_type = #{senderRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "receiver_id = #{receiverId,jdbcType=BIGINT},",
          "receiver_unread_count = #{receiverUnreadCount,jdbcType=INTEGER},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(GroupMemberDetail record);
}