package cn.xinzhili.chat.dao;

import cn.xinzhili.chat.model.MessageSession;
import cn.xinzhili.chat.model.MessageSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MessageSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int countByExample(MessageSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int deleteByExample(MessageSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    @Update({
        "update s_message.t_message_session",
        "set deleted_at = now()",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    @Select({
        "insert into s_message.t_message_session (session_id, user_id, ",
        "role_type, ",
        "user_status, ",
        "unread_status, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{sessionId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{roleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{userStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{unreadStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})", 
        " returning id"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    long insertReturningId(MessageSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    @Insert({
        "insert into s_message.t_message_session (session_id, user_id, ",
        "role_type, ",
        "user_status, ",
        "unread_status, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{sessionId,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{roleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{userStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{unreadStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(MessageSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    long insertSelectiveReturningId(MessageSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int insertSelective(MessageSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    List<MessageSession> selectByExample(MessageSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    @Select({
        "select",
        "id, session_id, user_id, role_type, user_status, unread_status, created_at, ",
        "updated_at, deleted_at",
        "from s_message.t_message_session",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.xinzhili.chat.dao.MessageSessionMapper.BaseResultMap")
    MessageSession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") MessageSession record, @Param("example") MessageSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int updateByExample(@Param("record") MessageSession record, @Param("example") MessageSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    int updateByPrimaryKeySelective(MessageSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_message_session
     *
     * @mbggenerated Sat May 12 11:22:50 CST 2018
     */
    @Update({
        "update s_message.t_message_session",
        "set session_id = #{sessionId,jdbcType=BIGINT},",
          "user_id = #{userId,jdbcType=BIGINT},",
          "role_type = #{roleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "user_status = #{userStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "unread_status = #{unreadStatus,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MessageSession record);
}