package cn.xinzhili.chat.dao;

import cn.xinzhili.chat.model.Session;
import cn.xinzhili.chat.model.SessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int countByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int deleteByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Update({
        "update s_message.t_session",
        "set deleted_at = now()",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Select({
        "insert into s_message.t_session (initiator_id, initiator_role_type, ",
        "organization_id, type, ",
        "session_type, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{initiatorId,jdbcType=BIGINT}, #{initiatorRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{organizationId,jdbcType=BIGINT}, #{type,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{sessionType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})", 
        " returning id"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    long insertReturningId(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Insert({
        "insert into s_message.t_session (initiator_id, initiator_role_type, ",
        "organization_id, type, ",
        "session_type, ",
        "created_at, updated_at, ",
        "deleted_at)",
        "values (#{initiatorId,jdbcType=BIGINT}, #{initiatorRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{organizationId,jdbcType=BIGINT}, #{type,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{sessionType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    long insertSelectiveReturningId(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int insertSelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    List<Session> selectByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Select({
        "select",
        "id, initiator_id, initiator_role_type, organization_id, type, session_type, ",
        "created_at, updated_at, deleted_at",
        "from s_message.t_session",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("cn.xinzhili.chat.dao.SessionMapper.BaseResultMap")
    Session selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    int updateByPrimaryKeySelective(Session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_message.t_session
     *
     * @mbggenerated Tue May 08 17:07:36 CST 2018
     */
    @Update({
        "update s_message.t_session",
        "set initiator_id = #{initiatorId,jdbcType=BIGINT},",
          "initiator_role_type = #{initiatorRoleType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "organization_id = #{organizationId,jdbcType=BIGINT},",
          "type = #{type,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "session_type = #{sessionType,jdbcType=SMALLINT,typeHandler=cn.xinzhili.xutils.mybatis.typehandlers.EnumCodeHandler},",
          "created_at = #{createdAt,jdbcType=TIMESTAMP},",
          "updated_at = #{updatedAt,jdbcType=TIMESTAMP},",
          "deleted_at = #{deletedAt,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Session record);
}